config/routes.rb
StaffList::Application.routes.draw do
  resources :staffs

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  validates :name, :presence => true
  default_scope :order => 'name'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @staffs }
    end
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
    @staff = Staff.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/new
  # GET /staffs/new.json
  def new
    @staff = Staff.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/1/edit
  def edit
    @staff = Staff.find(params[:id])
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(params[:staff])

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render json: @staff, status: :created, location: @staff }
      else
        format.html { render action: "new" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /staffs/1
  # PUT /staffs/1.json
  def update
    @staff = Staff.find(params[:id])

    respond_to do |format|
      if @staff.update_attributes(params[:staff])
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy

    respond_to do |format|
      format.html { redirect_to staffs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
  <title>Staff List</title>
  <%= stylesheet_link_tag    "bootstrap", "layout" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body class="container">
	<header>
		<h1>Simple Staff List <span class="subhead">with nice ui</span></h1>
	</header>

	<section>
		<%= yield %>
	</section>

	<footer class="pagefoot">
		<p>Garth Colasurdo</p>
	</footer>
</body>
</html>

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation" class="alert-message block-message error">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :name %>
		<div class="input">
    <%= f.text_field :name %>
		<span class="help-inline">Name is required</span>
		</div>
  </div>
  <div class="clearfix">
    <%= f.label :dept %>
		<div class="input">
    <%= f.text_field :dept %>
		</div>
  </div>
  <div class="clearfix">
    <%= f.label :phone %>
		<div class="input">
    <%= f.text_field :phone %>
		</div>
  </div>
  <div class="clearfix">
    <%= f.label :email %>
		<div class="input">
    <%= f.text_field :email %>
		</div>
  </div>
  <div class="actions">
		<%= f.submit :class => "btn primary" %>
		<%= link_to 'Back', staffs_path, :class => "btn" %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<div class="row">
	<nav class="span4">
		<h3>Options:</h3>
	</nav>

	<article class="span12">
		<h2>Editing staff</h2>
		<%= render 'form' %>
	</article>
</div>

app/views/staffs/index.html.erb
<div class="row">
	<nav class="span4">
		<h3>Options:</h3>
	</nav>

	<article class="span12">
		<h2>Staff Listing <span class="subhead"><%= link_to 'add staff', new_staff_path %></span></h2>
		<table class="zebra-striped">
		  <tr>
		    <th>Name</th>
		    <th>Dept</th>
		    <th>Phone</th>
		    <th>Email</th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>

		<% @staffs.each do |staff| %>
		  <tr>
		    <td><%= staff.name %></td>
		    <td><%= staff.dept %></td>
		    <td><%= staff.phone %></td>
		    <td><%= staff.email %></td>
		    <td><%= link_to 'Show', staff %></td>
		    <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
		    <td><%= link_to 'Destroy', staff, confirm: 'Are you sure?', method: :delete %></td>
		  </tr>
		<% end %>
		</table>
	</article>
</div>

app/views/staffs/new.html.erb
<div class="row">
	<nav class="span4">
		<h3>Options:</h3>
	</nav>

	<article class="span12">
		<h2>New staff</h2>
		<%= render 'form' %>
	</article>
</div>

app/views/staffs/show.html.erb
<div class="row">
	<nav class="span4">
		<h3>Options:</h3>
		<ul>
			<li><%= link_to 'Edit', edit_staff_path(@staff) %></li>
			<li><%= link_to 'Staff List', staffs_path %></li>
	</nav>

	<article class="span12">
	<p id="notice" class="alert-message block-message success"><%= notice %></p>

	<p>
	  <b>Name:</b>
	  <%= @staff.name %>
	</p>

	<p>
	  <b>Dept:</b>
	  <%= @staff.dept %>
	</p>

	<p>
	  <b>Phone:</b>
	  <%= @staff.phone %>
	</p>

	<p>
	  <b>Email:</b>
	  <%= @staff.email %>
	</p>
	</article>
</div>